[[main]]
    name = "Home"
    pageRef = "/"
    weight = 1
[[main]]
    name = "La asociaci√≥n"
    pageRef = "/associazione/"
    weight = 2
    identifier = "associazione"

[[main]]
    name = "La sede"
    pageRef = "/associazione/sede/"
    weight = 1
    parent = "associazione"

[[main]]
    name = "Estatuto"
    pageRef = "/associazione/statuto/"
    weight = 2
    parent = "associazione"
[[main]]
    name = "Actividades"
    pageRef = "/attivita/"
    weight = 3
[[main]]
    name = "Proyectos"
    pageRef = "/progetti/"
    weight = 4
[[main]]
    name = "Fotogaleria"
    pageRef = "/photogallery/"
    weight = 5
[[main]]
    name = "Asociate"
    url = "/associazione/associati"
    weight = 6
[[main]]
    name = "Shop"
    url = "https://shop.olografix.org/"
    weight = 7
    [main.params]
        external = true
[[main]]
    name = "Visita el viejo sitio"
    url = "https://web.archive.org/web/20241002224544/https://www.olografix.org/"
    weight = 8
    [main.params]
        fullwidthVisible = false
        external = true