[[main]]
    name = "Home"
    pageRef = "/"
    weight = 1
[[main]]
    name = "The association"
    pageRef = "/associazione/"
    weight = 2
[[main]]
    name = "Activities"
    pageRef = "/attivita/"
    weight = 3
[[main]]
    name = "Projects"
    pageRef = "/progetti/"
    weight = 4
[[main]]
    name = "Photogallery"
    pageRef = "/photogallery/"
    weight = 5
[[main]]
    name = "Join us"
    url = "/associazione/associati"
    weight = 6
[[main]]
    name = "Shop"
    url = "https://shop.olografix.org/"
    weight = 7
    [main.params]
        external = true
[[main]]
    name = "Visit the old website"
    url = "https://web.archive.org/web/20241002224544/https://www.olografix.org/"
    weight = 8
    [main.params]
        fullwidthVisible = false
        external = true